name: Deploy to DEV
on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - dev2
jobs:
  Deploy-to-DEV:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: RUN COMMAND
      run: echo "DEPLOY TO DEV"
