name: Deploy to DEV
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Deploy-to-DEV:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Show NPM Version
      run: npm -v
    - name: Install app packages
      run: |
        echo "::group::Install app packages"
        npm install
        echo "::endgroup::"
    - name: Build app
      run: |
        echo "::group::Build app"
        set +e
        npm run build
        set -e
        echo "::endgroup::"
    - name: RUN COMMAND
      run: echo "DEPLOY TO DEV"
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: |
        echo "::group::Adding Known Hosts"
        ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        echo "::endgroup::"
    - name: Try remove echo command
      run: ssh root@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'echo "test" >> $HOME/test.txt'
    - name: Copy build folder
      run: |
        echo "::group::Copy build folder"
        rsync -arvz -e 'ssh -p ${{ secrets.SSH_PORT }}' ./build/ root@${{ secrets.SSH_HOST }}:/root/build/
        echo "::endgroup::"
