name: Deploy to DEV
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Deploy-to-DEV:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: RUN COMMAND
      run: echo "DEPLOY TO DEV"
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
